baseurl: ""
url: "https://aloso.github.io/"
future: true
highlighter: rouge

asciidoctor:
  attributes:
  - idprefix=_
  - source-highlighter=rouge

plugins:
  - jekyll-asciidoc
  - jekyll-time-to-read
  - jekyll-redirect-from
