title: Aloso's blog
description: Posts around the Rust programming language
baseurl: ""
url: "https://aloso.github.io/"
future: true
highlighter: rouge

exclude:
  - README.adoc
  - Gemfile

asciidoctor:
  attributes:
    - idprefix=_
    - source-highlighter=rouge

plugins:
  - jekyll-asciidoc
  - jekyll-time-to-read
  - jekyll-redirect-from
